# OBJETIVO Elabora un programa que te solicite el ingreso y que muestre en ejecución, lo que se ha ingresado: Numero entero, Número flotante, Boleano, Cadena
# NOMBRES Y APELLIDOS: ISMAEL GILVER SOTO RODRIGUEZ

# TIPOS DE DATO
e=input("Ingrese numero entero: ")
f=input("Ingrese numero flotante: ")
b=input("Ingrese bolenao: ")
c=input("Ingrese cadena: ")
print(e)
print(f)
print(b)
print(c)


